cabal-version: 3.16
name: hamal
version: 0.1.0.0
license: BSD-3-Clause
license-file: LICENSE
author: atree4728
maintainer: atree.public@gmail.com
category: Language
build-type: Simple
extra-doc-files: README.md

common defaults
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wredundant-constraints
    -Wmissing-export-lists
    -Wpartial-fields
    -Werror=missing-deriving-strategies
    -Wunused-packages
    -Winvalid-haddock
    -Wredundant-bang-patterns
    -Woperator-whitespace
    -Wredundant-strictness-flags
    -Wterm-variable-capture
    -Wdefaulted-exception-context
    -fhide-source-paths

  default-extensions:
    BlockArguments
    DuplicateRecordFields
    MultiWayIf
    NoFieldSelectors
    OverloadedRecordDot
    OverloadedStrings
    RecordWildCards
    StrictData
    ViewPatterns

  default-language: GHC2024
  build-depends: base

library
  import: defaults
  -- cabal-gild: discover src
  exposed-modules:
    Frontend.Lexer
    Syntax
    Type

  build-tool-depends:
    alex:alex,
    happy:happy,

  build-depends:
    array,
    bytestring,

  hs-source-dirs: src

executable hamal
  import: defaults
  main-is: Main.hs
  build-depends:
    bytestring,
    hamal,

  hs-source-dirs: app

test-suite hamal-test
  import: defaults
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  build-depends: hamal
